// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sftp} from '../models';
import {context} from '../models';

export function Connect(arg1:sftp.ConnectRequest):Promise<sftp.ConnectResponse>;

export function DeleteFile(arg1:sftp.DeleteFileRequest):Promise<sftp.DeleteFileResponse>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:sftp.DownloadRequest):Promise<sftp.DownloadResponse>;

export function ListFiles(arg1:sftp.ListFilesRequest):Promise<sftp.ListFilesResponse>;

export function ListLocalFiles(arg1:sftp.LocalListFilesRequest):Promise<sftp.LocalListFilesResponse>;

export function Mkdir(arg1:sftp.MkdirRequest):Promise<sftp.MkdirResponse>;

export function Rename(arg1:sftp.RenameRequest):Promise<sftp.RenameResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UploadFile(arg1:sftp.UploadRequest):Promise<sftp.UploadResponse>;
