// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['sftp']['SFTPManager']['Connect'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['sftp']['SFTPManager']['DeleteFile'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['sftp']['SFTPManager']['Disconnect'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['sftp']['SFTPManager']['DownloadFile'](arg1);
}

export function GetTransferState(arg1) {
  return window['go']['sftp']['SFTPManager']['GetTransferState'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['sftp']['SFTPManager']['ListFiles'](arg1);
}

export function ListLocalFiles(arg1) {
  return window['go']['sftp']['SFTPManager']['ListLocalFiles'](arg1);
}

export function Mkdir(arg1) {
  return window['go']['sftp']['SFTPManager']['Mkdir'](arg1);
}

export function Rename(arg1) {
  return window['go']['sftp']['SFTPManager']['Rename'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['sftp']['SFTPManager']['ResumeDownload'](arg1);
}

export function ResumeUpload(arg1) {
  return window['go']['sftp']['SFTPManager']['ResumeUpload'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['sftp']['SFTPManager']['UploadFile'](arg1);
}
