// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['config']['ConfigManager']['AddServer'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['config']['ConfigManager']['DeleteServer'](arg1);
}

export function ExportServers() {
  return window['go']['config']['ConfigManager']['ExportServers']();
}

export function GetServers() {
  return window['go']['config']['ConfigManager']['GetServers']();
}

export function ImportServers(arg1) {
  return window['go']['config']['ConfigManager']['ImportServers'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['config']['ConfigManager']['ToggleFavorite'](arg1);
}

export function UpdateServer(arg1) {
  return window['go']['config']['ConfigManager']['UpdateServer'](arg1);
}
