// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function AddServer(arg1:config.AddServerRequest):Promise<config.AddServerResponse>;

export function DeleteServer(arg1:config.DeleteServerRequest):Promise<config.DeleteServerResponse>;

export function GetServers():Promise<config.GetServersResponse>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleFavorite(arg1:config.ToggleFavoriteRequest):Promise<config.ToggleFavoriteResponse>;

export function UpdateServer(arg1:config.UpdateServerRequest):Promise<config.UpdateServerResponse>;
