// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['ssh']['SSHService']['Connect'](arg1);
}

export function CreateShell(arg1) {
  return window['go']['ssh']['SSHService']['CreateShell'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['ssh']['SSHService']['Disconnect'](arg1);
}

export function GetClient(arg1) {
  return window['go']['ssh']['SSHService']['GetClient'](arg1);
}

export function GetLatency(arg1) {
  return window['go']['ssh']['SSHService']['GetLatency'](arg1);
}

export function IsConnected(arg1) {
  return window['go']['ssh']['SSHService']['IsConnected'](arg1);
}

export function ResizeTerminal(arg1) {
  return window['go']['ssh']['SSHService']['ResizeTerminal'](arg1);
}

export function WriteToSession(arg1) {
  return window['go']['ssh']['SSHService']['WriteToSession'](arg1);
}
