// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ssh} from '../models';
import {context} from '../models';

export function Connect(arg1:ssh.ConnectRequest):Promise<ssh.ConnectResponse>;

export function Disconnect(arg1:string):Promise<void>;

export function GetClient(arg1:string):Promise<ssh.Client>;

export function IsConnected(arg1:string):Promise<ssh.IsConnectedResponse>;

export function ResizeTerminal(arg1:ssh.ResizeRequest):Promise<ssh.ResizeResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function WriteToSession(arg1:ssh.WriteRequest):Promise<ssh.WriteResponse>;
