// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ssh} from '../models';

export function Connect(arg1:ssh.ConnectRequest):Promise<ssh.ConnectResponse>;

export function CreateShell(arg1:ssh.CreateShellRequest):Promise<ssh.CreateShellResponse>;

export function Disconnect(arg1:string):Promise<void>;

export function GetClient(arg1:string):Promise<ssh.Client>;

export function GetHostKeyCallback(arg1:string):Promise<ssh.HostKeyCallback>;

export function GetLatency(arg1:ssh.GetLatencyRequest):Promise<ssh.GetLatencyResponse>;

export function IsConnected(arg1:string):Promise<ssh.IsConnectedResponse>;

export function ResizeTerminal(arg1:ssh.ResizeRequest):Promise<ssh.ResizeResponse>;

export function TrustHostKey(arg1:ssh.TrustHostKeyRequest):Promise<ssh.TrustHostKeyResponse>;

export function WriteToSession(arg1:ssh.WriteRequest):Promise<ssh.WriteResponse>;
