// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DockerAction(arg1) {
  return window['go']['monitor']['MonitorService']['DockerAction'](arg1);
}

export function GetDockerContainers(arg1) {
  return window['go']['monitor']['MonitorService']['GetDockerContainers'](arg1);
}

export function GetDockerLogs(arg1) {
  return window['go']['monitor']['MonitorService']['GetDockerLogs'](arg1);
}

export function GetDockerStats(arg1) {
  return window['go']['monitor']['MonitorService']['GetDockerStats'](arg1);
}

export function GetProcesses(arg1) {
  return window['go']['monitor']['MonitorService']['GetProcesses'](arg1);
}

export function GetResourceUsage(arg1) {
  return window['go']['monitor']['MonitorService']['GetResourceUsage'](arg1);
}

export function GetSystemInfo(arg1) {
  return window['go']['monitor']['MonitorService']['GetSystemInfo'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['monitor']['MonitorService']['KillProcess'](arg1);
}

export function StartMonitor(arg1) {
  return window['go']['monitor']['MonitorService']['StartMonitor'](arg1);
}

export function StopMonitor(arg1) {
  return window['go']['monitor']['MonitorService']['StopMonitor'](arg1);
}
