// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';

export function DockerAction(arg1:monitor.DockerActionRequest):Promise<monitor.DockerActionResponse>;

export function GetDockerContainers(arg1:monitor.GetDockerRequest):Promise<monitor.GetDockerResponse>;

export function GetDockerLogs(arg1:monitor.DockerLogsRequest):Promise<monitor.DockerLogsResponse>;

export function GetDockerStats(arg1:monitor.DockerStatsRequest):Promise<monitor.DockerStatsResponse>;

export function GetProcesses(arg1:monitor.GetProcessesRequest):Promise<monitor.GetProcessesResponse>;

export function GetResourceUsage(arg1:string):Promise<monitor.ResourceUsage>;

export function GetSystemInfo(arg1:string):Promise<monitor.SystemInfo>;

export function KillProcess(arg1:monitor.KillProcessRequest):Promise<monitor.KillProcessResponse>;

export function StartMonitor(arg1:monitor.StartMonitorRequest):Promise<monitor.StartMonitorResponse>;

export function StopMonitor(arg1:monitor.StopMonitorRequest):Promise<monitor.StopMonitorResponse>;
