// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';

export function GetConnections(arg1:monitor.GetConnectionsRequest):Promise<monitor.GetConnectionsResponse>;

export function GetNetTraffic(arg1:monitor.GetNetTrafficRequest):Promise<monitor.GetNetTrafficResponse>;

export function Ping(arg1:monitor.PingRequest):Promise<monitor.PingResponse>;

export function StartNetMonitor(arg1:monitor.StartNetMonitorRequest):Promise<monitor.StartNetMonitorResponse>;

export function StopNetMonitor(arg1:monitor.StopNetMonitorRequest):Promise<monitor.StopNetMonitorResponse>;

export function Traceroute(arg1:monitor.TracerouteRequest):Promise<monitor.TracerouteResponse>;
