// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnections(arg1) {
  return window['go']['monitor']['NetworkService']['GetConnections'](arg1);
}

export function GetNetTraffic(arg1) {
  return window['go']['monitor']['NetworkService']['GetNetTraffic'](arg1);
}

export function Ping(arg1) {
  return window['go']['monitor']['NetworkService']['Ping'](arg1);
}

export function StartNetMonitor(arg1) {
  return window['go']['monitor']['NetworkService']['StartNetMonitor'](arg1);
}

export function StopNetMonitor(arg1) {
  return window['go']['monitor']['NetworkService']['StopNetMonitor'](arg1);
}

export function Traceroute(arg1) {
  return window['go']['monitor']['NetworkService']['Traceroute'](arg1);
}
