// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {sftp} from '../models';
import {ssh} from '../models';

export function GetConfigManager():Promise<config.ConfigManager>;

export function GetSFTPManager():Promise<sftp.SFTPManager>;

export function GetSSHService():Promise<ssh.SSHService>;
