// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigManager() {
  return window['go']['main']['App']['GetConfigManager']();
}

export function GetSFTPManager() {
  return window['go']['main']['App']['GetSFTPManager']();
}

export function GetSSHService() {
  return window['go']['main']['App']['GetSSHService']();
}
