// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vnc} from '../models';

export function SetSSHProvider(arg1:vnc.SSHClientProvider):Promise<void>;

export function StartProxy(arg1:vnc.StartProxyRequest):Promise<vnc.StartProxyResponse>;

export function StopProxy(arg1:vnc.StopProxyRequest):Promise<vnc.StopProxyResponse>;
