// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetSSHProvider(arg1) {
  return window['go']['vnc']['Proxy']['SetSSHProvider'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['vnc']['Proxy']['StartProxy'](arg1);
}

export function StopProxy(arg1) {
  return window['go']['vnc']['Proxy']['StopProxy'](arg1);
}
