// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCache(arg1) {
  return window['go']['autocomplete']['AutoCompleteService']['ClearCache'](arg1);
}

export function Complete(arg1) {
  return window['go']['autocomplete']['AutoCompleteService']['Complete'](arg1);
}

export function FetchCommands(arg1) {
  return window['go']['autocomplete']['AutoCompleteService']['FetchCommands'](arg1);
}
