// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCache(arg1:autocomplete.ClearCacheRequest):Promise<autocomplete.ClearCacheResponse>;

export function Complete(arg1:autocomplete.CompleteRequest):Promise<autocomplete.CompleteResponse>;

export function FetchCommands(arg1:autocomplete.FetchCommandsRequest):Promise<autocomplete.FetchCommandsResponse>;
